/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package buff;

import Frame.MainFrame;
import java.awt.Rectangle;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JScrollBar;
import tools.CheckIfInt;

/**
 *
 * @author branko.scekic
 */
public class Podesavanja extends javax.swing.JFrame {

    /**
     * Creates new form Podesavanja
     */
    Buff modbus;

    public Podesavanja(Buff modbus) {
        initComponents();
        URL iconURL = getClass().getResource("/image/truckBar.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());

        Rectangle bounds = jScrollPane1.getViewport().getViewRect();

        JScrollBar horizontal = jScrollPane1.getHorizontalScrollBar();
        horizontal.setValue((horizontal.getMaximum() - bounds.width) / 8);

        jScrollPane1.getVerticalScrollBar().setUnitIncrement(18);
        jScrollPane1.getHorizontalScrollBar().setUnitIncrement(12);

        this.modbus = modbus;
    
        config = new Config();
        loadData();
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldK1Izdato = new javax.swing.JTextField();
        jTextFieldK1Zadato = new javax.swing.JTextField();
        jTextFieldK2Zadato = new javax.swing.JTextField();
        jTextFieldK2Izdato = new javax.swing.JTextField();
        jTextFieldK3Zadato = new javax.swing.JTextField();
        jTextFieldK3Izdato = new javax.swing.JTextField();
        jTextFieldK4Izdato = new javax.swing.JTextField();
        jTextFieldK4Zadato = new javax.swing.JTextField();
        jTextFieldK5Zadato = new javax.swing.JTextField();
        jTextFieldK5Izdato = new javax.swing.JTextField();
        jTextFieldK7Zadato = new javax.swing.JTextField();
        jTextFieldK7Izdato = new javax.swing.JTextField();
        jTextFieldK6Zadato = new javax.swing.JTextField();
        jTextFieldK6Izdato = new javax.swing.JTextField();
        jTextFieldK8Zadato = new javax.swing.JTextField();
        jTextFieldK9Zadato = new javax.swing.JTextField();
        jTextFieldK9Izdato = new javax.swing.JTextField();
        jTextFieldK8Izdato = new javax.swing.JTextField();
        jTextFieldZadatoUkupno = new javax.swing.JTextField();
        jTextFieldIzdatoUkupno = new javax.swing.JTextField();
        jTextFieldm3Izdato = new javax.swing.JTextField();
        jTextFieldRucAut = new javax.swing.JTextField();
        jTextFieldCementSilos2 = new javax.swing.JTextField();
        jTextFieldKompresor = new javax.swing.JTextField();
        jTextFieldAgregat16_32 = new javax.swing.JTextField();
        jTextFieldSpreman = new javax.swing.JTextField();
        jTextFieldZadatoSarze = new javax.swing.JTextField();
        jTextFieldIzdatoSarze = new javax.swing.JTextField();
        jTextFieldBrOtpreme = new javax.swing.JTextField();
        jTextFieldHidropumpa = new javax.swing.JTextField();
        jTextFieldMesalica = new javax.swing.JTextField();
        jTextFieldAgregat0_4 = new javax.swing.JTextField();
        jTextFieldAditivVagaZatvorena = new javax.swing.JTextField();
        jTextFieldAditivVagaPuna = new javax.swing.JTextField();
        jTextFieldAditivSilos = new javax.swing.JTextField();
        jTextFieldAditivSilos2 = new javax.swing.JTextField();
        jTextFieldAditivSilos1 = new javax.swing.JTextField();
        jTextFieldVodaSilos1 = new javax.swing.JTextField();
        jTextFieldVodaSilos2 = new javax.swing.JTextField();
        jTextFieldVodaVagaPuna = new javax.swing.JTextField();
        jTextFieldVodaVagaZatvorena = new javax.swing.JTextField();
        jTextFieldNumberStatus = new javax.swing.JTextField();
        jTextFieldAgregat8_16 = new javax.swing.JTextField();
        jTextFieldAgregatNumber = new javax.swing.JTextField();
        jTextFieldCementSilos1 = new javax.swing.JTextField();
        jTextFieldMesalicaOtvorena = new javax.swing.JTextField();
        jTextField61 = new javax.swing.JTextField();
        jTextFieldCementVagaZatvorena = new javax.swing.JTextField();
        jTextFieldCementSilos = new javax.swing.JTextField();
        jTextFieldCementVagaPuna = new javax.swing.JTextField();
        jTextFieldAgregat4_8 = new javax.swing.JTextField();
        jTextFieldAgregatTraka = new javax.swing.JTextField();
        jTextFieldDisplej = new javax.swing.JTextField();
        jTextFieldAgregatText = new javax.swing.JTextField();
        jTextFieldCementText = new javax.swing.JTextField();
        jTextFieldVodaText = new javax.swing.JTextField();
        jTextFieldAditivText = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jTextFieldm3Izdato1 = new javax.swing.JTextField();
        jTextFieldSpreman1 = new javax.swing.JTextField();
        jLabelNumberCement = new javax.swing.JTextField();
        jTextFieldNumberVoda = new javax.swing.JTextField();
        jTextFieldNumberAditiv = new javax.swing.JTextField();
        jTextFieldK10Zadato = new javax.swing.JTextField();
        jTextFieldK10Izdato = new javax.swing.JTextField();
        jTextFieldRotacija = new javax.swing.JTextField();
        jTextFieldK10Izdato1 = new javax.swing.JTextField();
        jTextFieldBrOtpreme1 = new javax.swing.JTextField();
        jTextFieldBrOtpreme2 = new javax.swing.JTextField();
        jTextFieldBrOtpreme3 = new javax.swing.JTextField();
        jTextFieldBrOtpreme4 = new javax.swing.JTextField();
        jTextFieldBrOtpreme5 = new javax.swing.JTextField();
        jTextFieldBrOtpreme6 = new javax.swing.JTextField();
        jTextFieldBrOtpreme7 = new javax.swing.JTextField();
        jTextFieldBrOtpreme8 = new javax.swing.JTextField();
        jTextFieldBrOtpreme9 = new javax.swing.JTextField();
        jTextFieldMesalicaZatvorena1 = new javax.swing.JTextField();
        jTextFieldBrOtpreme10 = new javax.swing.JTextField();
        jTextFieldBrOtpreme11 = new javax.swing.JTextField();
        jTextFieldBrOtpreme12 = new javax.swing.JTextField();
        jLabelStartProces = new javax.swing.JLabel();
        jTextFieldIPPLC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabelTestComm = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldUpisUBazu = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldOsvezavanje = new javax.swing.JTextField();
        jComboBoxIdPLC = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldStartAddressRegister = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldDigitIn = new javax.swing.JTextField();
        jCheckBoxCitanjePaketa = new javax.swing.JCheckBox();
        jCheckBoxPojedinacno = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jTextFieldK1Izdato.setEditable(false);
        jTextFieldK1Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK1Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK1Izdato.setText("1");
        jPanel3.add(jTextFieldK1Izdato);
        jTextFieldK1Izdato.setBounds(90, 90, 60, 30);

        jTextFieldK1Zadato.setEditable(false);
        jTextFieldK1Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK1Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK1Zadato.setText("0");
        jPanel3.add(jTextFieldK1Zadato);
        jTextFieldK1Zadato.setBounds(90, 60, 60, 30);

        jTextFieldK2Zadato.setEditable(false);
        jTextFieldK2Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK2Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK2Zadato.setText("2");
        jPanel3.add(jTextFieldK2Zadato);
        jTextFieldK2Zadato.setBounds(260, 60, 60, 30);

        jTextFieldK2Izdato.setEditable(false);
        jTextFieldK2Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK2Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK2Izdato.setText("3");
        jPanel3.add(jTextFieldK2Izdato);
        jTextFieldK2Izdato.setBounds(260, 90, 60, 30);

        jTextFieldK3Zadato.setEditable(false);
        jTextFieldK3Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK3Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK3Zadato.setText("4");
        jPanel3.add(jTextFieldK3Zadato);
        jTextFieldK3Zadato.setBounds(410, 60, 60, 30);

        jTextFieldK3Izdato.setEditable(false);
        jTextFieldK3Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK3Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK3Izdato.setText("5");
        jPanel3.add(jTextFieldK3Izdato);
        jTextFieldK3Izdato.setBounds(410, 90, 60, 30);

        jTextFieldK4Izdato.setEditable(false);
        jTextFieldK4Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK4Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK4Izdato.setText("7");
        jPanel3.add(jTextFieldK4Izdato);
        jTextFieldK4Izdato.setBounds(570, 90, 60, 30);

        jTextFieldK4Zadato.setEditable(false);
        jTextFieldK4Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK4Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK4Zadato.setText("6");
        jPanel3.add(jTextFieldK4Zadato);
        jTextFieldK4Zadato.setBounds(570, 60, 60, 30);

        jTextFieldK5Zadato.setEditable(false);
        jTextFieldK5Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK5Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK5Zadato.setText("8");
        jPanel3.add(jTextFieldK5Zadato);
        jTextFieldK5Zadato.setBounds(740, 60, 60, 30);

        jTextFieldK5Izdato.setEditable(false);
        jTextFieldK5Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK5Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK5Izdato.setText("9");
        jPanel3.add(jTextFieldK5Izdato);
        jTextFieldK5Izdato.setBounds(740, 90, 60, 30);

        jTextFieldK7Zadato.setEditable(false);
        jTextFieldK7Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK7Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK7Zadato.setText("12");
        jPanel3.add(jTextFieldK7Zadato);
        jTextFieldK7Zadato.setBounds(1030, 60, 60, 30);

        jTextFieldK7Izdato.setEditable(false);
        jTextFieldK7Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK7Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK7Izdato.setText("13");
        jPanel3.add(jTextFieldK7Izdato);
        jTextFieldK7Izdato.setBounds(1030, 90, 60, 30);

        jTextFieldK6Zadato.setEditable(false);
        jTextFieldK6Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK6Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK6Zadato.setText("10");
        jPanel3.add(jTextFieldK6Zadato);
        jTextFieldK6Zadato.setBounds(870, 60, 60, 30);

        jTextFieldK6Izdato.setEditable(false);
        jTextFieldK6Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK6Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK6Izdato.setText("11");
        jPanel3.add(jTextFieldK6Izdato);
        jTextFieldK6Izdato.setBounds(870, 90, 60, 30);

        jTextFieldK8Zadato.setEditable(false);
        jTextFieldK8Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK8Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK8Zadato.setText("14");
        jPanel3.add(jTextFieldK8Zadato);
        jTextFieldK8Zadato.setBounds(1200, 60, 60, 30);

        jTextFieldK9Zadato.setEditable(false);
        jTextFieldK9Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK9Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK9Zadato.setText("16");
        jPanel3.add(jTextFieldK9Zadato);
        jTextFieldK9Zadato.setBounds(1330, 60, 60, 30);

        jTextFieldK9Izdato.setEditable(false);
        jTextFieldK9Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK9Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK9Izdato.setText("17");
        jPanel3.add(jTextFieldK9Izdato);
        jTextFieldK9Izdato.setBounds(1330, 90, 60, 30);

        jTextFieldK8Izdato.setEditable(false);
        jTextFieldK8Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK8Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK8Izdato.setText("15");
        jPanel3.add(jTextFieldK8Izdato);
        jTextFieldK8Izdato.setBounds(1200, 90, 60, 30);

        jTextFieldZadatoUkupno.setEditable(false);
        jTextFieldZadatoUkupno.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldZadatoUkupno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldZadatoUkupno.setText("20");
        jPanel3.add(jTextFieldZadatoUkupno);
        jTextFieldZadatoUkupno.setBounds(1700, 30, 60, 30);

        jTextFieldIzdatoUkupno.setEditable(false);
        jTextFieldIzdatoUkupno.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIzdatoUkupno.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldIzdatoUkupno.setText("21");
        jPanel3.add(jTextFieldIzdatoUkupno);
        jTextFieldIzdatoUkupno.setBounds(1700, 60, 60, 30);

        jTextFieldm3Izdato.setEditable(false);
        jTextFieldm3Izdato.setBackground(new java.awt.Color(204, 255, 255));
        jTextFieldm3Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldm3Izdato.setText("22");
        jPanel3.add(jTextFieldm3Izdato);
        jTextFieldm3Izdato.setBounds(280, 180, 60, 30);

        jTextFieldRucAut.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldRucAut.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldRucAut.setText("0 prekidac");
        jPanel3.add(jTextFieldRucAut);
        jTextFieldRucAut.setBounds(1790, 50, 90, 30);

        jTextFieldCementSilos2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCementSilos2.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldCementSilos2.setText("2");
        jPanel3.add(jTextFieldCementSilos2);
        jTextFieldCementSilos2.setBounds(610, 310, 80, 30);

        jTextFieldKompresor.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldKompresor.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldKompresor.setText("18");
        jPanel3.add(jTextFieldKompresor);
        jTextFieldKompresor.setBounds(1090, 860, 90, 30);

        jTextFieldAgregat16_32.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregat16_32.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAgregat16_32.setText("24");
        jPanel3.add(jTextFieldAgregat16_32);
        jTextFieldAgregat16_32.setBounds(380, 510, 50, 30);

        jTextFieldSpreman.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSpreman.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldSpreman.setText("20 Kraj");
        jPanel3.add(jTextFieldSpreman);
        jTextFieldSpreman.setBounds(310, 830, 90, 30);

        jTextFieldZadatoSarze.setEditable(false);
        jTextFieldZadatoSarze.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldZadatoSarze.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldZadatoSarze.setText("24");
        jPanel3.add(jTextFieldZadatoSarze);
        jTextFieldZadatoSarze.setBounds(610, 470, 60, 30);

        jTextFieldIzdatoSarze.setEditable(false);
        jTextFieldIzdatoSarze.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldIzdatoSarze.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldIzdatoSarze.setText("25");
        jPanel3.add(jTextFieldIzdatoSarze);
        jTextFieldIzdatoSarze.setBounds(1110, 180, 60, 30);

        jTextFieldBrOtpreme.setEditable(false);
        jTextFieldBrOtpreme.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme.setText("35 mesalica text");
        jPanel3.add(jTextFieldBrOtpreme);
        jTextFieldBrOtpreme.setBounds(850, 730, 110, 30);

        jTextFieldHidropumpa.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldHidropumpa.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldHidropumpa.setText("16");
        jPanel3.add(jTextFieldHidropumpa);
        jTextFieldHidropumpa.setBounds(1080, 750, 90, 30);

        jTextFieldMesalica.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMesalica.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldMesalica.setText("17");
        jPanel3.add(jTextFieldMesalica);
        jTextFieldMesalica.setBounds(1180, 750, 90, 30);

        jTextFieldAgregat0_4.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregat0_4.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAgregat0_4.setText("23");
        jPanel3.add(jTextFieldAgregat0_4);
        jTextFieldAgregat0_4.setBounds(320, 510, 50, 30);

        jTextFieldAditivVagaZatvorena.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAditivVagaZatvorena.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAditivVagaZatvorena.setText("14");
        jPanel3.add(jTextFieldAditivVagaZatvorena);
        jTextFieldAditivVagaZatvorena.setBounds(770, 500, 80, 30);

        jTextFieldAditivVagaPuna.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAditivVagaPuna.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAditivVagaPuna.setText("15");
        jPanel3.add(jTextFieldAditivVagaPuna);
        jTextFieldAditivVagaPuna.setBounds(940, 510, 80, 30);

        jTextFieldAditivSilos.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAditivSilos.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAditivSilos.setText("13");
        jPanel3.add(jTextFieldAditivSilos);
        jTextFieldAditivSilos.setBounds(860, 560, 80, 30);

        jTextFieldAditivSilos2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAditivSilos2.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAditivSilos2.setText("12");
        jPanel3.add(jTextFieldAditivSilos2);
        jTextFieldAditivSilos2.setBounds(920, 320, 80, 30);

        jTextFieldAditivSilos1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAditivSilos1.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAditivSilos1.setText("11");
        jPanel3.add(jTextFieldAditivSilos1);
        jTextFieldAditivSilos1.setBounds(800, 320, 80, 30);

        jTextFieldVodaSilos1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldVodaSilos1.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldVodaSilos1.setText("6");
        jPanel3.add(jTextFieldVodaSilos1);
        jTextFieldVodaSilos1.setBounds(700, 490, 80, 30);

        jTextFieldVodaSilos2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldVodaSilos2.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldVodaSilos2.setText("7");
        jTextFieldVodaSilos2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVodaSilos2ActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldVodaSilos2);
        jTextFieldVodaSilos2.setBounds(1110, 350, 80, 30);

        jTextFieldVodaVagaPuna.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldVodaVagaPuna.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldVodaVagaPuna.setText("10");
        jPanel3.add(jTextFieldVodaVagaPuna);
        jTextFieldVodaVagaPuna.setBounds(1110, 560, 80, 30);

        jTextFieldVodaVagaZatvorena.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldVodaVagaZatvorena.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldVodaVagaZatvorena.setText("9");
        jPanel3.add(jTextFieldVodaVagaZatvorena);
        jTextFieldVodaVagaZatvorena.setBounds(1180, 500, 80, 30);

        jTextFieldNumberStatus.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNumberStatus.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldNumberStatus.setText("8");
        jPanel3.add(jTextFieldNumberStatus);
        jTextFieldNumberStatus.setBounds(1030, 500, 80, 30);

        jTextFieldAgregat8_16.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregat8_16.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAgregat8_16.setText("21");
        jPanel3.add(jTextFieldAgregat8_16);
        jTextFieldAgregat8_16.setBounds(190, 510, 50, 30);

        jTextFieldAgregatNumber.setEditable(false);
        jTextFieldAgregatNumber.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregatNumber.setText("34");
        jPanel3.add(jTextFieldAgregatNumber);
        jTextFieldAgregatNumber.setBounds(240, 900, 80, 30);

        jTextFieldCementSilos1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCementSilos1.setForeground(new java.awt.Color(51, 102, 255));
        jTextFieldCementSilos1.setText("1");
        jPanel3.add(jTextFieldCementSilos1);
        jTextFieldCementSilos1.setBounds(520, 310, 80, 30);

        jTextFieldMesalicaOtvorena.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMesalicaOtvorena.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldMesalicaOtvorena.setText("27");
        jPanel3.add(jTextFieldMesalicaOtvorena);
        jTextFieldMesalicaOtvorena.setBounds(1010, 770, 50, 30);

        jTextField61.setBackground(new java.awt.Color(204, 204, 204));
        jTextField61.setForeground(new java.awt.Color(51, 51, 255));
        jTextField61.setText("28");
        jPanel3.add(jTextField61);
        jTextField61.setBounds(1000, 820, 50, 30);

        jTextFieldCementVagaZatvorena.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCementVagaZatvorena.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldCementVagaZatvorena.setText("4");
        jPanel3.add(jTextFieldCementVagaZatvorena);
        jTextFieldCementVagaZatvorena.setBounds(600, 560, 80, 30);

        jTextFieldCementSilos.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCementSilos.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldCementSilos.setText("3");
        jPanel3.add(jTextFieldCementSilos);
        jTextFieldCementSilos.setBounds(700, 310, 80, 30);

        jTextFieldCementVagaPuna.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCementVagaPuna.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldCementVagaPuna.setText("5");
        jTextFieldCementVagaPuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCementVagaPunaActionPerformed(evt);
            }
        });
        jPanel3.add(jTextFieldCementVagaPuna);
        jTextFieldCementVagaPuna.setBounds(510, 490, 80, 30);

        jTextFieldAgregat4_8.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregat4_8.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAgregat4_8.setText("22");
        jPanel3.add(jTextFieldAgregat4_8);
        jTextFieldAgregat4_8.setBounds(260, 510, 50, 30);

        jTextFieldAgregatTraka.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregatTraka.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldAgregatTraka.setText("25");
        jPanel3.add(jTextFieldAgregatTraka);
        jTextFieldAgregatTraka.setBounds(270, 600, 80, 30);

        jTextFieldDisplej.setEditable(false);
        jTextFieldDisplej.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldDisplej.setText("26");
        jPanel3.add(jTextFieldDisplej);
        jTextFieldDisplej.setBounds(1100, 440, 80, 30);

        jTextFieldAgregatText.setEditable(false);
        jTextFieldAgregatText.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAgregatText.setText("33");
        jPanel3.add(jTextFieldAgregatText);
        jTextFieldAgregatText.setBounds(1410, 230, 80, 30);

        jTextFieldCementText.setEditable(false);
        jTextFieldCementText.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldCementText.setText("27");
        jPanel3.add(jTextFieldCementText);
        jTextFieldCementText.setBounds(860, 170, 80, 30);

        jTextFieldVodaText.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldVodaText.setText("29");
        jPanel3.add(jTextFieldVodaText);
        jTextFieldVodaText.setBounds(290, 290, 80, 30);

        jTextFieldAditivText.setEditable(false);
        jTextFieldAditivText.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldAditivText.setText("31");
        jPanel3.add(jTextFieldAditivText);
        jTextFieldAditivText.setBounds(1410, 170, 80, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save_48x48.png"))); // NOI18N
        jButton2.setText("   Sacuvaj");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(1370, 850, 250, 110);

        jTextFieldm3Izdato1.setEditable(false);
        jTextFieldm3Izdato1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldm3Izdato1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldm3Izdato1.setText("23");
        jPanel3.add(jTextFieldm3Izdato1);
        jTextFieldm3Izdato1.setBounds(610, 170, 60, 30);

        jTextFieldSpreman1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldSpreman1.setForeground(new java.awt.Color(0, 51, 255));
        jTextFieldSpreman1.setText("19 Spreman");
        jPanel3.add(jTextFieldSpreman1);
        jTextFieldSpreman1.setBounds(310, 790, 90, 30);

        jLabelNumberCement.setEditable(false);
        jLabelNumberCement.setBackground(new java.awt.Color(204, 204, 204));
        jLabelNumberCement.setText("28");
        jPanel3.add(jLabelNumberCement);
        jLabelNumberCement.setBounds(860, 430, 80, 30);

        jTextFieldNumberVoda.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNumberVoda.setText("30");
        jPanel3.add(jTextFieldNumberVoda);
        jTextFieldNumberVoda.setBounds(270, 660, 80, 30);

        jTextFieldNumberAditiv.setEditable(false);
        jTextFieldNumberAditiv.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldNumberAditiv.setText("32");
        jPanel3.add(jTextFieldNumberAditiv);
        jTextFieldNumberAditiv.setBounds(1410, 200, 80, 30);

        jTextFieldK10Zadato.setEditable(false);
        jTextFieldK10Zadato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK10Zadato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK10Zadato.setText("18");
        jPanel3.add(jTextFieldK10Zadato);
        jTextFieldK10Zadato.setBounds(1610, 30, 60, 30);

        jTextFieldK10Izdato.setEditable(false);
        jTextFieldK10Izdato.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK10Izdato.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK10Izdato.setText("19");
        jPanel3.add(jTextFieldK10Izdato);
        jTextFieldK10Izdato.setBounds(1410, 260, 80, 30);

        jTextFieldRotacija.setEditable(false);
        jTextFieldRotacija.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldRotacija.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldRotacija.setText("26");
        jTextFieldRotacija.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.add(jTextFieldRotacija);
        jTextFieldRotacija.setBounds(220, 750, 40, 20);

        jTextFieldK10Izdato1.setEditable(false);
        jTextFieldK10Izdato1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldK10Izdato1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldK10Izdato1.setText("19");
        jPanel3.add(jTextFieldK10Izdato1);
        jTextFieldK10Izdato1.setBounds(1610, 60, 60, 30);

        jTextFieldBrOtpreme1.setEditable(false);
        jTextFieldBrOtpreme1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme1.setText("36 1 m3");
        jPanel3.add(jTextFieldBrOtpreme1);
        jTextFieldBrOtpreme1.setBounds(460, 770, 110, 30);

        jTextFieldBrOtpreme2.setEditable(false);
        jTextFieldBrOtpreme2.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme2.setText("37   2 m3");
        jPanel3.add(jTextFieldBrOtpreme2);
        jTextFieldBrOtpreme2.setBounds(570, 770, 110, 30);

        jTextFieldBrOtpreme3.setEditable(false);
        jTextFieldBrOtpreme3.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme3.setText("38 3 m3");
        jPanel3.add(jTextFieldBrOtpreme3);
        jTextFieldBrOtpreme3.setBounds(690, 770, 110, 30);

        jTextFieldBrOtpreme4.setEditable(false);
        jTextFieldBrOtpreme4.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme4.setText("39 4 m3");
        jPanel3.add(jTextFieldBrOtpreme4);
        jTextFieldBrOtpreme4.setBounds(810, 770, 110, 30);

        jTextFieldBrOtpreme5.setEditable(false);
        jTextFieldBrOtpreme5.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme5.setText("40 5 m3");
        jPanel3.add(jTextFieldBrOtpreme5);
        jTextFieldBrOtpreme5.setBounds(460, 810, 110, 30);

        jTextFieldBrOtpreme6.setEditable(false);
        jTextFieldBrOtpreme6.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme6.setText("41 6 m3");
        jPanel3.add(jTextFieldBrOtpreme6);
        jTextFieldBrOtpreme6.setBounds(570, 810, 110, 30);

        jTextFieldBrOtpreme7.setEditable(false);
        jTextFieldBrOtpreme7.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme7.setText("42 7 m3");
        jPanel3.add(jTextFieldBrOtpreme7);
        jTextFieldBrOtpreme7.setBounds(690, 810, 110, 30);

        jTextFieldBrOtpreme8.setEditable(false);
        jTextFieldBrOtpreme8.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme8.setText("43 8 m3");
        jPanel3.add(jTextFieldBrOtpreme8);
        jTextFieldBrOtpreme8.setBounds(810, 810, 110, 30);

        jTextFieldBrOtpreme9.setEditable(false);
        jTextFieldBrOtpreme9.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme9.setText("55");
        jPanel3.add(jTextFieldBrOtpreme9);
        jTextFieldBrOtpreme9.setBounds(690, 210, 50, 30);

        jTextFieldMesalicaZatvorena1.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldMesalicaZatvorena1.setForeground(new java.awt.Color(51, 51, 255));
        jTextFieldMesalicaZatvorena1.setText("29");
        jPanel3.add(jTextFieldMesalicaZatvorena1);
        jTextFieldMesalicaZatvorena1.setBounds(1010, 870, 50, 30);

        jTextFieldBrOtpreme10.setEditable(false);
        jTextFieldBrOtpreme10.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme10.setText("44 9 m3");
        jPanel3.add(jTextFieldBrOtpreme10);
        jTextFieldBrOtpreme10.setBounds(460, 850, 110, 30);

        jTextFieldBrOtpreme11.setEditable(false);
        jTextFieldBrOtpreme11.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme11.setText("53");
        jPanel3.add(jTextFieldBrOtpreme11);
        jTextFieldBrOtpreme11.setBounds(610, 210, 50, 30);

        jTextFieldBrOtpreme12.setEditable(false);
        jTextFieldBrOtpreme12.setBackground(new java.awt.Color(204, 204, 204));
        jTextFieldBrOtpreme12.setText("51");
        jPanel3.add(jTextFieldBrOtpreme12);
        jTextFieldBrOtpreme12.setBounds(530, 210, 50, 30);

        jLabelStartProces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/mainFrame.png"))); // NOI18N
        jLabelStartProces.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelStartProces.setOpaque(true);
        jPanel3.add(jLabelStartProces);
        jLabelStartProces.setBounds(0, 0, 1900, 950);

        jTextFieldIPPLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIPPLCActionPerformed(evt);
            }
        });

        jLabel2.setText("IP adresa PLK");

        jButton1.setText("Test komunikacije");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("adresa registra koji kada se postavi na >1 sadrzaj se preuzima: ");

        jTextFieldUpisUBazu.setText("1000");
        jTextFieldUpisUBazu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUpisUBazuActionPerformed(evt);
            }
        });

        jLabel4.setText("Vreme ciklusa ocitavanja sa PLK(  * 100 ms):");

        jComboBoxIdPLC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "84", "85", "86", "87", "88", "89", "90", "91", "92", "93", "94", "95", "96", "97", "98", "99", "100", "101", "102", "103", "104", "105", "106", "107", "108", "109", "110", "111", "112", "113", "114", "115", "116", "117", "118", "119", "120", "121", "122", "123", "124", "125", "126", "127", "128", "129", "130", "131", "132", "133", "134", "135", "136", "137", "138", "139", "140", "141", "142", "143", "144", "145", "146", "147", "148", "149", "150", "151", "152", "153", "154", "155", "156", "157", "158", "159", "160", "161", "162", "163", "164", "165", "166", "167", "168", "169", "170", "181", "182", "183", "184", "185", "186", "187", "188", "189", "190", "191", "192", "193", "194", "195", "196", "197", "198", "199", "200", "201", "202", "203", "204", "205", "206", "207", "208", "209", "210", "211", "212", "213", "214", "215", "216", "217", "218", "219", "220", "221", "222", "223", "224", "225", "226", "227", "228", "229", "230", "231", "232", "233", "234", "235", "236", "237", "238", "239", "240", "241", "242", "243", "244", "245", "246", "247", "248", "249", "250", "251", "252", "253", "254", "255" }));

        jLabel5.setText("Izaberite id plc");

        jLabel6.setText("Start adresa registra: ");

        jTextFieldStartAddressRegister.setText("0");

        jLabel8.setForeground(java.awt.Color.blue);
        jLabel8.setText("Start adresa digitalnih ulaza: ");

        jTextFieldDigitIn.setForeground(java.awt.Color.blue);
        jTextFieldDigitIn.setText("0");

        buttonGroup1.add(jCheckBoxCitanjePaketa);
        jCheckBoxCitanjePaketa.setSelected(true);
        jCheckBoxCitanjePaketa.setText("Citanje paketa");

        buttonGroup1.add(jCheckBoxPojedinacno);
        jCheckBoxPojedinacno.setText("CitanjePojedinacno");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(279, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldIPPLC)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxIdPLC, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addComponent(jLabelTestComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldStartAddressRegister)
                    .addComponent(jTextFieldDigitIn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 280, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCheckBoxCitanjePaketa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBoxPojedinacno, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldUpisUBazu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldOsvezavanje, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldUpisUBazu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jButton1)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 21, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldIPPLC)
                                    .addComponent(jLabelTestComm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldOsvezavanje))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldDigitIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBoxIdPLC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldStartAddressRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(jCheckBoxCitanjePaketa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxPojedinacno)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 946, Short.MAX_VALUE)
                .addContainerGap())
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1632, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (modbus.ping()) {
            jLabelTestComm.setText("Konekcija ok");
        } else {
            jLabelTestComm.setText("Nema komunikacije");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldCementVagaPunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCementVagaPunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCementVagaPunaActionPerformed

    private void jTextFieldVodaSilos2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVodaSilos2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVodaSilos2ActionPerformed

    private void jTextFieldUpisUBazuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUpisUBazuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldUpisUBazuActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        if(jCheckBoxCitanjePaketa.isSelected()){
            typeReadDI=1;
        }else{
            typeReadDI=5;
        }
        
        config.saveProp(jTextFieldIPPLC.getText(), jComboBoxIdPLC.getSelectedItem().toString(),
                jTextFieldStartAddressRegister.getText(), jTextFieldUpisUBazu.getText(),
                jTextFieldDigitIn.getText(), jTextFieldOsvezavanje.getText(), Integer.toString(typeReadDI));
        MainFrame.setujPodesavanjaModbus = true;

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextFieldIPPLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIPPLCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIPPLCActionPerformed

    private void loadData() {
        jTextFieldIPPLC.setText(config.getIp());
        jComboBoxIdPLC.setSelectedItem(config.getId());
        jTextFieldStartAddressRegister.setText(config.getStartAddressRegister());
        jTextFieldDigitIn.setText(config.getStartAddressDigitalInput());
        jTextFieldOsvezavanje.setText(config.getvremeCitanjaMS());
        jTextFieldUpisUBazu.setText(config.getStartnaAdresaRegistraZaBazu());
        typeReadDI=CheckIfInt.checkIfInt(config.getReadDI());
        if(typeReadDI>=1 && typeReadDI<2){
            jCheckBoxCitanjePaketa.setSelected(true);
        }else{
            jCheckBoxPojedinacno.setSelected(true);
            
        }
    }

    /**
     * @param args the command line arguments
     */
    /*
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Podesavanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Podesavanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Podesavanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Podesavanja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
     */
 /* Create and display the form */
 /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Podesavanja().setVisible(true);
            }
        });
    }
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxCitanjePaketa;
    private javax.swing.JCheckBox jCheckBoxPojedinacno;
    private javax.swing.JComboBox<String> jComboBoxIdPLC;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jLabelNumberCement;
    private javax.swing.JLabel jLabelStartProces;
    private javax.swing.JLabel jLabelTestComm;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField61;
    private javax.swing.JTextField jTextFieldAditivSilos;
    private javax.swing.JTextField jTextFieldAditivSilos1;
    private javax.swing.JTextField jTextFieldAditivSilos2;
    private javax.swing.JTextField jTextFieldAditivText;
    private javax.swing.JTextField jTextFieldAditivVagaPuna;
    private javax.swing.JTextField jTextFieldAditivVagaZatvorena;
    private javax.swing.JTextField jTextFieldAgregat0_4;
    private javax.swing.JTextField jTextFieldAgregat16_32;
    private javax.swing.JTextField jTextFieldAgregat4_8;
    private javax.swing.JTextField jTextFieldAgregat8_16;
    private javax.swing.JTextField jTextFieldAgregatNumber;
    private javax.swing.JTextField jTextFieldAgregatText;
    private javax.swing.JTextField jTextFieldAgregatTraka;
    private javax.swing.JTextField jTextFieldBrOtpreme;
    private javax.swing.JTextField jTextFieldBrOtpreme1;
    private javax.swing.JTextField jTextFieldBrOtpreme10;
    private javax.swing.JTextField jTextFieldBrOtpreme11;
    private javax.swing.JTextField jTextFieldBrOtpreme12;
    private javax.swing.JTextField jTextFieldBrOtpreme2;
    private javax.swing.JTextField jTextFieldBrOtpreme3;
    private javax.swing.JTextField jTextFieldBrOtpreme4;
    private javax.swing.JTextField jTextFieldBrOtpreme5;
    private javax.swing.JTextField jTextFieldBrOtpreme6;
    private javax.swing.JTextField jTextFieldBrOtpreme7;
    private javax.swing.JTextField jTextFieldBrOtpreme8;
    private javax.swing.JTextField jTextFieldBrOtpreme9;
    private javax.swing.JTextField jTextFieldCementSilos;
    private javax.swing.JTextField jTextFieldCementSilos1;
    private javax.swing.JTextField jTextFieldCementSilos2;
    private javax.swing.JTextField jTextFieldCementText;
    private javax.swing.JTextField jTextFieldCementVagaPuna;
    private javax.swing.JTextField jTextFieldCementVagaZatvorena;
    private javax.swing.JTextField jTextFieldDigitIn;
    private javax.swing.JTextField jTextFieldDisplej;
    private javax.swing.JTextField jTextFieldHidropumpa;
    private javax.swing.JTextField jTextFieldIPPLC;
    private javax.swing.JTextField jTextFieldIzdatoSarze;
    private javax.swing.JTextField jTextFieldIzdatoUkupno;
    private javax.swing.JTextField jTextFieldK10Izdato;
    private javax.swing.JTextField jTextFieldK10Izdato1;
    private javax.swing.JTextField jTextFieldK10Zadato;
    private javax.swing.JTextField jTextFieldK1Izdato;
    private javax.swing.JTextField jTextFieldK1Zadato;
    private javax.swing.JTextField jTextFieldK2Izdato;
    private javax.swing.JTextField jTextFieldK2Zadato;
    private javax.swing.JTextField jTextFieldK3Izdato;
    private javax.swing.JTextField jTextFieldK3Zadato;
    private javax.swing.JTextField jTextFieldK4Izdato;
    private javax.swing.JTextField jTextFieldK4Zadato;
    private javax.swing.JTextField jTextFieldK5Izdato;
    private javax.swing.JTextField jTextFieldK5Zadato;
    private javax.swing.JTextField jTextFieldK6Izdato;
    private javax.swing.JTextField jTextFieldK6Zadato;
    private javax.swing.JTextField jTextFieldK7Izdato;
    private javax.swing.JTextField jTextFieldK7Zadato;
    private javax.swing.JTextField jTextFieldK8Izdato;
    private javax.swing.JTextField jTextFieldK8Zadato;
    private javax.swing.JTextField jTextFieldK9Izdato;
    private javax.swing.JTextField jTextFieldK9Zadato;
    private javax.swing.JTextField jTextFieldKompresor;
    private javax.swing.JTextField jTextFieldMesalica;
    private javax.swing.JTextField jTextFieldMesalicaOtvorena;
    private javax.swing.JTextField jTextFieldMesalicaZatvorena1;
    private javax.swing.JTextField jTextFieldNumberAditiv;
    private javax.swing.JTextField jTextFieldNumberStatus;
    private javax.swing.JTextField jTextFieldNumberVoda;
    private javax.swing.JTextField jTextFieldOsvezavanje;
    private javax.swing.JTextField jTextFieldRotacija;
    private javax.swing.JTextField jTextFieldRucAut;
    private javax.swing.JTextField jTextFieldSpreman;
    private javax.swing.JTextField jTextFieldSpreman1;
    private javax.swing.JTextField jTextFieldStartAddressRegister;
    private javax.swing.JTextField jTextFieldUpisUBazu;
    private javax.swing.JTextField jTextFieldVodaSilos1;
    private javax.swing.JTextField jTextFieldVodaSilos2;
    private javax.swing.JTextField jTextFieldVodaText;
    private javax.swing.JTextField jTextFieldVodaVagaPuna;
    private javax.swing.JTextField jTextFieldVodaVagaZatvorena;
    private javax.swing.JTextField jTextFieldZadatoSarze;
    private javax.swing.JTextField jTextFieldZadatoUkupno;
    private javax.swing.JTextField jTextFieldm3Izdato;
    private javax.swing.JTextField jTextFieldm3Izdato1;
    // End of variables declaration//GEN-END:variables

    private final Config config;
    private int typeReadDI=0;
}
