/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DbService.RegtabliceService;
import java.awt.Cursor;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author brasa
 */
public class AddRegTab extends javax.swing.JFrame {

    /**
     * Creates new form AddMasinista
     * @param regTablicaDb
     */
    public AddRegTab(RegtabliceService regTablicaDb) {
        initComponents();
        URL iconURL = getClass().getResource("/image/truckBar.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        jTextFieldGradiliste = new JTextField();
        result = new JLabel();
        result.setText("");
      
        this.regTablicaDb = regTablicaDb;
        readTablice();
        rowSorter = new TableRowSorter<>(jTable1.getModel());
        jTable1.setRowSorter(rowSorter);
        addFilter();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTextFieldSlova = new javax.swing.JTextField();
        jTextFieldBrojevi = new javax.swing.JTextField();
        jTextFieldMesto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        jButton1.setText("Izlaz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(490, 510, 102, 33);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Add.png"))); // NOI18N
        jButton2.setText("Dodaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(0, 510, 89, 33);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));

        jTextFieldSlova.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSlovaKeyReleased(evt);
            }
        });

        jTextFieldBrojevi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldBrojeviKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jTextFieldMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldBrojevi, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldBrojevi, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldSlova, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(96, 4, 390, 90);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "rb", "tablice"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(100, 120, 390, 330);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Left-right.png"))); // NOI18N
        jButton3.setText("Povezi vozace i vozila");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(190, 500, 220, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Kamion-sa.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 540);

        setSize(new java.awt.Dimension(605, 549));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBrojeviKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldBrojeviKeyReleased
        jTextFieldGradiliste.setText(jTextFieldMesto.getText() +jTextFieldBrojevi.getText() + jTextFieldSlova.getText());
    }//GEN-LAST:event_jTextFieldBrojeviKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldSlovaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSlovaKeyReleased
        jTextFieldGradiliste.setText(jTextFieldMesto.getText() +jTextFieldBrojevi.getText() + jTextFieldSlova.getText());
    }//GEN-LAST:event_jTextFieldSlovaKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        result.setText(jTextFieldMesto.getText()+ " " + jTextFieldBrojevi.getText()+"-" + jTextFieldSlova.getText());
        int dialogButton = JOptionPane.showConfirmDialog(null, "Da li zelite da dodate reg tablice " + result.getText() + " ?");

        if (dialogButton == JOptionPane.YES_OPTION) { //The ISSUE is here
            //gradilisteDb.addNewGradiliste(jTextFieldGradiliste.getText(), jTextFieldMesto.getText(), jTextFieldAdresa.getText());
            regTablicaDb.addNewTablice(result.getText());
            result.setText("");
            jTextFieldGradiliste.setText("");
            jTextFieldMesto.setText("");
            jTextFieldBrojevi.setText("");
            jTextFieldSlova.setText("");
            readTablice();
            rowSorter = new TableRowSorter<>(jTable1.getModel());
            jTable1.setRowSorter(rowSorter);
            addFilter();
            
            MainFrame.osveziBazuRegTab = true;
            Baza.osveziPrikaz =true;
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        try {
            vozaciVozaila = new VozaciVozila();
            vozaciVozaila.show(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Doslo je do greske do komunikacije sa bazom");
        }
        setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_jButton3ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBrojevi;
    private javax.swing.JTextField jTextFieldMesto;
    private javax.swing.JTextField jTextFieldSlova;
    // End of variables declaration//GEN-END:variables

    RegtabliceService regTablicaDb;
    private TableRowSorter<TableModel> rowSorter;
    private final JTextField jTextFieldGradiliste;
    private final JLabel result;
    private VozaciVozila vozaciVozaila;
    
    private void readTablice() {

        List<Db.Regtablice> result = regTablicaDb.getRegTablice();
        Object[][] obj = new Object[result.size()][2];

        int i = 0;

        for (Db.Regtablice auto : result) {
            obj[i][0] = i + 1;
            obj[i][1] = auto.getTablice();

            i++;
        }

        DefaultTableModel model = new DefaultTableModel(obj, new Object[]{"r.b.", "Reg tablice"});
        jTable1.setModel(model);
        jTable1.setRowMargin(4);
        jTable1.setRowHeight(40);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(45);

    }
    
     private void addFilter() {
        jTextFieldGradiliste.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jTextFieldGradiliste.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jTextFieldGradiliste.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

        });
    }
}
