/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import DbService.KorisnikService;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author brasa
 */
public class Korisnici extends javax.swing.JFrame {

    /**
     * Creates new form Korisnici
     */
    public Korisnici() {
        initComponents();
        URL iconURL = getClass().getResource("/image/truckBar.png");
        ImageIcon icon = new ImageIcon(iconURL);
        this.setIconImage(icon.getImage());
        
        userDb = new KorisnikService();
        setDefaultTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    public void setDefaultTable(){    
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, new Boolean(true), null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "r.b.", "ime", " prezime",  "kor. ime", "L1", "L2", "a", "lozinka"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
   
        
        jTable1.setRowMargin(4);
        jTable1.setRowHeight(40);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(35);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(35);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(35);
        
 
        
        try{
            loadTable();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, " Doslo je do greske prilikom ocitavanja iz baze ");
        }
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        Izlaz = new javax.swing.JButton();
        jButtonAddUser = new javax.swing.JButton();
        jButtonDeleteuser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setBackground(new java.awt.Color(153, 153, 153));
        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Korisnici");
        jLabel11.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jLabel11.setOpaque(true);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null,  new Boolean(true), null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null,  new Boolean(true), null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTable1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTable1MouseExited(evt);
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTable1KeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Blue key.png"))); // NOI18N
        jButton1.setText("Otkljucaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Save.png"))); // NOI18N
        jButtonSave.setText("Sacuvaj");
        jButtonSave.setEnabled(false);
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        Izlaz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Exit.png"))); // NOI18N
        Izlaz.setText("Izlaz");
        Izlaz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IzlazActionPerformed(evt);
            }
        });

        jButtonAddUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/People.png"))); // NOI18N
        jButtonAddUser.setText("Dodaj korisnika");
        jButtonAddUser.setEnabled(false);
        jButtonAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddUserActionPerformed(evt);
            }
        });

        jButtonDeleteuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Erase.png"))); // NOI18N
        jButtonDeleteuser.setText("Obrisi korisnika");
        jButtonDeleteuser.setEnabled(false);
        jButtonDeleteuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteuserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddUser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeleteuser, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Izlaz, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSave, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButtonSave)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Izlaz)
                    .addComponent(jButtonDeleteuser)
                    .addComponent(jButtonAddUser))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void loadTable() {
        List<Db.Korisnik> result = userDb.getKorisnici();
        Object[][] obj = new Object[result.size()][9];

        int i = 0;

        for (Db.Korisnik auto : result) {
            obj[i][0] = i + 1;
            obj[i][1] = result.get(i).getIme();
            obj[i][2] = result.get(i).getPrezime();
            obj[i][3] = result.get(i).getUsername();
            obj[i][4] = result.get(i).getL1();
            obj[i][5] = result.get(i).getL2();
            obj[i][6] = result.get(i).getAdmin();
            obj[i][7] = userDb.decryptedPass(result.get(i).getLozinka());
            obj[i][8] = result.get(i).getIdkorisnik();
            
            i++;
        }

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            obj,
            new String [] {
                "r.b.", "ime", " prezime", "kor. ime" , "Izvestaji", "Baza", "Administrator", "lozinka",""
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class , java.lang.Object.class
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        
        jTable1.setRowMargin(4);
        jTable1.setRowHeight(40);
        jTable1.getColumnModel().getColumn(0).setMaxWidth(45);
        jTable1.getColumnModel().getColumn(4).setMaxWidth(75);
        jTable1.getColumnModel().getColumn(5).setMaxWidth(75);
        jTable1.getColumnModel().getColumn(6).setMaxWidth(75);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0);
        jTable1.getColumnModel().getColumn(8).setWidth(0);
        jTable1.getColumnModel().getColumn(8).setMaxWidth(0); 
        
        
       
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jTable1.setEnabled(true);
        jButtonSave.setEnabled(true);
        jButtonAddUser.setEnabled(true);
        jButtonDeleteuser.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Da li zelite da zapamtite promene?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            userDb.updateKorisnik(Integer.parseInt(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 8).toString()), 
                    Boolean.parseBoolean(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4).toString()), 
                    Boolean.parseBoolean(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5).toString()),
                    Boolean.parseBoolean(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6).toString()));
            loadTable();
        }
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void IzlazActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IzlazActionPerformed
        this.dispose();
    }//GEN-LAST:event_IzlazActionPerformed

    private void jButtonAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddUserActionPerformed
        addUsr = new NoviKorisnik();
        addUsr.show(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAddUserActionPerformed

    private void jTable1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseEntered
        uslovZaUpis = false;
    }//GEN-LAST:event_jTable1MouseEntered

    private void jTable1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseExited
        uslovZaUpis = true;
    }//GEN-LAST:event_jTable1MouseExited

    private void jTable1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyReleased
        int k = evt.getKeyCode();
        if(uslovZaUpis){
            switch (k) {
                case KeyEvent.VK_ENTER:
                    uslovZaUpis = false;
                    break;
                case KeyEvent.VK_A:
                    //korpa.x-=5;
                    //korpa.repaint();
                    break;
            }
        }
    }//GEN-LAST:event_jTable1KeyReleased

    private void jButtonDeleteuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteuserActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(null, "Da li zelite da obrisete korisnika ?", "Warning", dialogButton);
        if (dialogResult == JOptionPane.YES_OPTION) {
            userDb.deleteUser(Integer.parseInt(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 8).toString()));
            loadTable();
        }
        
    }//GEN-LAST:event_jButtonDeleteuserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Izlaz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddUser;
    private javax.swing.JButton jButtonDeleteuser;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
    private NoviKorisnik addUsr;
    public KorisnikService userDb;
    private boolean uslovZaUpis;
}
